on:
  push:
    branches:
      - main

jobs:
  create_stripe_customer:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "create_stripe_customer"
      folder: "create_stripe_customer"
      resource: users/{userId}

  create_stripe_product:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "create_stripe_product"
      folder: "create_stripe_product"
      resource: matches/{matchId}

  create_match_link:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "create_match_link"
      folder: "create_match_link"
      resource: matches/{matchId}


  schedule_prematch_notification:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_prematch_notification"
      folder: "notifications"
      resource: matches/{matchId}

  schedule_run_post_match_tasks:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_run_post_match_tasks"
      folder: "run_post_match_tasks"
      resource: matches/{matchId}

  clean_up_match:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "clean_up_match"
      folder: "match_crud_v2/clean_up_match"
      resource: matches/{matchId}
      firestore_event: document.delete

  schedule_start_voting_notification:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_start_voting_notification"
      folder: "notifications"
      resource: matches/{matchId}

  schedule_make_teams:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_make_teams"
      folder: "team_recommendations"
      resource: matches/{matchId}
