on:
  push:
    branches:
      - main

jobs:
  schedule_run_post_match_tasks:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_run_post_match_tasks"
      folder: "run_post_match_tasks"
      resource: matches/{matchId}

  schedule_start_voting_notification:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_start_voting_notification"
      folder: "notifications"
      resource: matches/{matchId}

  schedule_make_teams:
    uses: './.github/workflows/deploy-firestore-trigger-template.yaml'
    with:
      name: "schedule_make_teams"
      folder: "team_recommendations"
      resource: matches/{matchId}
