on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: app-engine

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Deploying to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/956073807168/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'deploy-cloud-functions@nutmeg-9099c.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
