on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      folder:
        required: true
        type: string
      secrets:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v2'

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            folder:
              - 'functions-python/${{ inputs.folder }}/**'
          list-files: 'csv'

      - id: 'auth'
        if: steps.changes.outputs.folder == 'true'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/956073807168/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'deploy-cloud-functions@nutmeg-9099c.iam.gserviceaccount.com'

      - id: 'deploy'
        if: steps.changes.outputs.folder == 'true'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          source_dir: functions-python/${{ inputs.folder }}
          name: ${{ inputs.name }}
          runtime: 'python37'
          region: europe-central2
          secret_environment_variables: STRIPE_PROD_KEY=projects/956073807168/secrets/stripeProdKey,STRIPE_TEST_KEY=projects/956073807168/secrets/stripeTestKey
